spiders/apps/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

spiders/apps/statistic/urls.py
from django.urls import path
from . import views

app_name = 'statistic'

urlpatterns = [
    path('', views.index, name='index'),
    path('date_filter/', views.date_filter, name='date_filter'),
    path('done_filter/', views.done_filter, name='done_filter')
]

spiders/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('statistic/', include('statistic.urls'))
]

spiders/apps/main/models.py
from django.db import models

# Create your models here.

spiders/apps/statistic/models.py
from django.db import models

# Create your models here.

spiders/apps/main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

spiders/apps/statistic/views.py
from django.shortcuts import render
from spiders.apps.statistic.Competitionmyteam import main
from datetime import datetime
pl_keys_friends=[1321, 1319, 1318, 1320]
def index(request):
    return render(request, 'statistic.html',{'spiders':main(),'friends':pl_keys_friends,'message':f"All source"})
def date_filter(request):
    date = datetime.strptime(request.POST['started_date'], '%Y-%m-%d')
    return render(request, 'statistic.html',{'spiders':main(1,date),'friends':pl_keys_friends,'message':f"Started with {request.POST['started_date']}"})
def done_filter(request):
    date = datetime.strptime(request.POST['started_date'], '%Y-%m-%d')
    return render(request, 'statistic.html',{'spiders':main(2,date),'friends':pl_keys_friends,'message':f"Done with {request.POST['started_date']}"})

spiders/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
      {% load static %}
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
    <script type="text/javascript">
      $(document).ready(function() { 
          $("table") 
          .tablesorter({widthFixed: true, widgets: ['zebra']}); 
      });
          </script>
  </head>

  <body>

    <nav class="site-header sticky-top py-1">
      <div class="container d-flex flex-column flex-md-row justify-content-between">
        <a class="py-2" href="{% url 'main:index' %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mx-auto"><circle cx="12" cy="12" r="10"></circle><line x1="14.31" y1="8" x2="20.05" y2="17.94"></line><line x1="9.69" y1="8" x2="21.17" y2="8"></line><line x1="7.38" y1="12" x2="13.12" y2="2.06"></line><line x1="9.69" y1="16" x2="3.95" y2="6.06"></line><line x1="14.31" y1="16" x2="2.83" y2="16"></line><line x1="16.62" y1="12" x2="10.88" y2="21.94"></line></svg>
        </a>
        <a class="py-2 d-none d-md-inline-block" href="{% url 'statistic:index' %}">Statistic</a>
{#        <a class="py-2 d-none d-md-inline-block" href="#">Product</a>#}
{#        <a class="py-2 d-none d-md-inline-block" href="#">Features</a>#}
{#        <a class="py-2 d-none d-md-inline-block" href="#">Enterprise</a>#}
{#        <a class="py-2 d-none d-md-inline-block" href="#">Support</a>#}
{#        <a class="py-2 d-none d-md-inline-block" href="#">Pricing</a>#}
{#        <a class="py-2 d-none d-md-inline-block" href="#">Cart</a>#}
      </div>
    </nav>

        {%block content%}
        {%endblock%}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'dist/js/jquery.tablesorter.min.js' %}"></script>
    <script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/holder.min.js' %}"></script>
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
  </body>
</html>

spiders/templates/index.html
{% extends 'base.html' %}
{% block title %}Main{% endblock %}
{% block content %}
{% load static %}
{% endblock %}

spiders/templates/statistic.html
{% extends 'base.html' %}
{% block title %}Main{% endblock %}
{% block content %}
{% load static %}
<script src="{% static 'dist/js/google_chart.js' %}"></script>
<script>document.addEventListener('DOMContentLoaded', () => {

  const getSort = ({ target }) => {
      const order = (target.dataset.order = -(target.dataset.order || -1));
      const index = [...target.parentNode.cells].indexOf(target);
      const collator = new Intl.Collator(['en', 'ru'], { numeric: true });
      const comparator = (index, order) => (a, b) => order * collator.compare(
          a.children[index].innerHTML,
          b.children[index].innerHTML
      );
      
      for(const tBody of target.closest('table').tBodies)
          tBody.append(...[...tBody.rows].sort(comparator(index, order)));

      for(const cell of target.parentNode.cells)
          cell.classList.toggle('sorted', cell === target);
  };
  
  document.querySelectorAll('.table_sort thead').forEach(tableTH => tableTH.addEventListener('click', () => getSort(event)));
  
});</script>
<style>
table {
  width: 100%;
  border-collapse:separate;
  border:solid black 1px;
  border-radius:12px;
  -moz-border-radius:12px;
  background-color:whitesmoke;
}

td, th {
  padding: 3px;
  text-align: center;
  border-left:solid black 1px;
  border-top:solid black 1px;
}

th {
  border-top: none;
}

td:first-child, th:first-child {
   border-left: none;
}
th.sorted[data-order="1"],
th.sorted[data-order="-1"] {
  position: relative;
}

th.sorted[data-order="1"]::after,
th.sorted[data-order="-1"]::after {
  right: 8px;
  position: absolute;
}

th.sorted[data-order="-1"]::after {
content: "▼"
}

th.sorted[data-order="1"]::after {
content: "▲"
}</style>
  <script>
   google.load("visualization", "1", {packages:["corechart"]});
   google.setOnLoadCallback(drawChart);
   function drawChart() {
    var data = google.visualization.arrayToDataTable([
     ['Spiders', 'Done source', 'Done Fix'],
{% for sp in spiders %}
     ['{{ sp.name }} {{ sp.minute }}-min',{{ sp.done_source }},{{ sp.done_fix }}],
        {% endfor %}
    ]);
    var options = {
     title: 'Performance',
     hAxis: {title: 'Spiders'},
     vAxis: {title: 'Sources'}
    };
    var chart = new google.visualization.ColumnChart(document.getElementById('oil'));
    chart.draw(data, options);
   }
  </script>
    <h2>{{ message }}</h2>
    <div id="oil" style="width:100%; height:650px;"></div>
    <table id='example' class="table tablesorter table_sort">
  <thead>
    <tr>
      <th class="sorted" scope="col">Id</th>
      <th class="sorted" scope="col">Spiders</th>
      <th class="sorted" scope="col">Done</th>
      <th class="sorted" scope="col">Open</th>
      <th class="sorted" scope="col">In progress</th>
      <th class="sorted" scope="col">Closed</th>
      <th class="sorted" scope="col">New source</th>
      <th class="sorted" scope="col">Fix</th>
      
      <th class="sorted" scope="col">Done source</th>
      <th class="sorted" scope="col">Done fix</th>
        <th class="sorted" scope="col">Percent fix</th>
      <th class="sorted" scope="col">Minutes</th>
    </tr>
  </thead>
  <tbody>
  {% for sp in spiders %}
<tr>
      <th scope="row">{{ sp.key }}</th>
      <td>{{ sp.name }}</td>
      <td>{{ sp.done }}</td>
      <td>{{ sp.open }}</td>
      <td>{{ sp.in_progress }}</td>
      <td>{{ sp.closed }}</td>
      <td>{{ sp.new }}</td>
      <td>{{ sp.fix }}</td>
      
      <td>{{ sp.done_source }}</td>
      <td>{{ sp.done_fix }}</td>
    <td>{{ sp.percent }}%</td>
      <td>{{ sp.minute }}</td>
    </tr>
        {% endfor %}
  </tbody>
</table>

            <form style="float: right" action={% url 'statistic:done_filter' %} method='POST'>
    {% csrf_token %}
  <div class="form-group">
    <label for="inputDate" >Done:</label>
    <input type="date" name="started_date" class="form-control">
      <button class="btn btn-primary btn-form" type="submit">Filter</button>
  </div>
</form>
    <form style="float: right" action={% url 'statistic:date_filter' %} method='POST'>
    {% csrf_token %}
  <div class="form-group">
    <label for="inputDate" >Started:</label>
    <input type="date" name="started_date" class="form-control">
      <button class="btn btn-primary btn-form" type="submit">Filter</button>
  </div>
</form>


{% endblock %}